spring.application.name=api

keycloak.url=${KEYCLOAK_URL:http://keycloak:8080}
keycloak.realm=${KEYCLOAK_REALM:reports-realm}
KEYCLOAK_ISSUER_URL=http://localhost
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URL}/realms/${keycloak.realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certsOAuth2 client registration

spring.security.oauth2.client.registration.keycloak.client-id=${KEYCLOAK_CLIENT_ID:reports-api}
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:oNwoLQdvJAvRcL89SydqCWCe5ry1jMgq}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openidOAuth2 client provider

spring.security.oauth2.client.provider.keycloak.token-uri=${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.authorization-uri=${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.user-info-uri=${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/userinfo