spring.application.name=api

keycloak.url=${KEYCLOAK_URL:http://keycloak:8080}
keycloak.realm=${KEYCLOAK_REALM:reports-realm}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.url}/realms/${keycloak.realm}

